/**
 * Basic Usage Example for OpenPhone API SDK
 * 
 * ⚠️ WARNING: This is NOT an official OpenPhone SDK.
 * This is an unofficial, community-created SDK.
 * 
 * ⚠️ WARNING: This SDK was primarily generated by AI.
 * Please review all code thoroughly before using in production.
 * Use at your own risk.
 */

import { OpenPhoneClient } from '@noobforal/openphone-api-sdk';

async function basicUsage() {
  // Initialize the client
  const client = new OpenPhoneClient({
    apiKey: process.env.OPENPHONE_API_KEY || 'your-api-key-here',
    baseUrl: 'https://api.openphone.com',
  });

  try {
    // List phone numbers
    console.log('📞 Listing phone numbers...');
    const phoneNumbers = await client.listPhoneNumbers();
    
    if (phoneNumbers.error) {
      console.error('Error listing phone numbers:', phoneNumbers.error);
      return;
    }
    
    console.log('Phone numbers:', phoneNumbers.data);

    // Get the first phone number ID for other operations
    const firstPhoneNumber = phoneNumbers.data?.phoneNumbers?.[0];
    if (!firstPhoneNumber) {
      console.log('No phone numbers found');
      return;
    }

    const phoneNumberId = firstPhoneNumber.id;
    console.log(`Using phone number: ${phoneNumberId}`);

    // List calls for this phone number
    console.log('\n📞 Listing calls...');
    const calls = await client.listCalls({
      phoneNumberId,
      participants: ['+1234567890'], // Replace with actual phone number
      maxResults: 10,
    });

    if (calls.error) {
      console.error('Error listing calls:', calls.error);
    } else {
      console.log('Calls:', calls.data);
    }

    // List messages for this phone number
    console.log('\n💬 Listing messages...');
    const messages = await client.listMessages({
      phoneNumberId,
      participants: ['+1234567890'], // Replace with actual phone number
      maxResults: 10,
    });

    if (messages.error) {
      console.error('Error listing messages:', messages.error);
    } else {
      console.log('Messages:', messages.data);
    }

    // List webhooks
    console.log('\n🔗 Listing webhooks...');
    const webhooks = await client.listWebhooks();

    if (webhooks.error) {
      console.error('Error listing webhooks:', webhooks.error);
    } else {
      console.log('Webhooks:', webhooks.data);
    }

  } catch (error) {
    console.error('Unexpected error:', error);
  }
}

// Run the example
if (import.meta.main) {
  basicUsage();
}
