/**
 * Send Message Example for OpenPhone API SDK
 * 
 * ⚠️ WARNING: This is NOT an official OpenPhone SDK.
 * This is an unofficial, community-created SDK.
 * 
 * ⚠️ WARNING: This SDK was primarily generated by AI.
 * Please review all code thoroughly before using in production.
 * Use at your own risk.
 */

import { OpenPhoneClient } from '@noobforal/openphone-api-sdk';

async function sendMessage() {
  const client = new OpenPhoneClient({
    apiKey: process.env.OPENPHONE_API_KEY || 'your-api-key-here',
  });

  try {
    // First, get available phone numbers
    console.log('📞 Getting phone numbers...');
    const phoneNumbers = await client.listPhoneNumbers();

    if (phoneNumbers.error) {
      console.error('Error getting phone numbers:', phoneNumbers.error);
      return;
    }

    const availableNumbers = phoneNumbers.data?.phoneNumbers || [];
    if (availableNumbers.length === 0) {
      console.log('No phone numbers available');
      return;
    }

    const phoneNumber = availableNumbers[0];
    console.log(`Using phone number: ${phoneNumber.id} (${phoneNumber.phoneNumber})`);

    // Send a message
    console.log('\n💬 Sending message...');
    const message = await client.sendMessage({
      content: 'Hello from the OpenPhone API SDK! This is a test message.',
      from: phoneNumber.id,
      to: ['+1234567890'], // Replace with actual recipient phone number
      setInboxStatus: 'done',
    });

    if (message.error) {
      console.error('Error sending message:', message.error);
    } else {
      console.log('Message sent successfully:', message.data);
    }

    // List recent messages to verify
    console.log('\n📋 Listing recent messages...');
    const recentMessages = await client.listMessages({
      phoneNumberId: phoneNumber.id,
      participants: ['+1234567890'], // Replace with actual phone number
      maxResults: 5,
    });

    if (recentMessages.error) {
      console.error('Error listing messages:', recentMessages.error);
    } else {
      console.log('Recent messages:', recentMessages.data);
    }

  } catch (error) {
    console.error('Unexpected error:', error);
  }
}

// Run the example
if (import.meta.main) {
  sendMessage();
}
