name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  release:
    types: [ published ]

jobs:
  # Lint and Test Job
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Download OpenAPI specification
        run: |
          curl -o openapi.json https://openphone-public-api-prod.s3.us-west-2.amazonaws.com/public/openphone-public-api-v1-prod.json

      - name: Generate TypeScript types
        run: npm run generate:types

      - name: Run linter
        run: npm run lint

      - name: Run formatter check
        run: npm run format:check

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 7

  # Build and Publish Job
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    needs: lint-and-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Download OpenAPI specification
        run: |
          curl -o openapi.json https://openphone-public-api-prod.s3.us-west-2.amazonaws.com/public/openphone-public-api-v1-prod.json

      - name: Build project
        run: npm run build

      - name: Setup Node.js for publishing
        uses: actions/setup-node@v5
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  # Release Job
  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build-and-publish
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Download build artifacts
        uses: actions/download-artifact@v5
        with:
          name: dist
          path: dist/

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.release.tag_name }}
          release_name: ${{ github.event.release.name }}
          body: |
            ## What's Changed
            
            This release includes:
            - TypeScript SDK for OpenPhone Public API
            - Full type safety with auto-generated types
            - Support for calls, messages, phone numbers, and webhooks
            - Modern ES modules with tree-shaking support
            - Node.js and npm compatibility
            
            ## Installation
            
            ```bash
            npm install @noobforal/openphone-api-sdk
            ```
            
            ## Usage
            
            ```typescript
            import { OpenPhoneClient } from '@noobforal/openphone-api-sdk';
            
            const client = new OpenPhoneClient({
              apiKey: 'your-api-key-here',
            });
            ```
          draft: false
          prerelease: false

  # Security Audit Job
  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        run: npm audit

      - name: Check for vulnerabilities
        run: |
          if npm audit --json | jq -e '.vulnerabilities | length > 0' > /dev/null; then
            echo "Security vulnerabilities found!"
            npm audit
            exit 1
          else
            echo "No security vulnerabilities found."
          fi