name: Pull Request Checks

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  pr-checks:
    name: PR Quality Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Download OpenAPI specification
        run: |
          curl -o openapi.json https://openphone-public-api-prod.s3.us-west-2.amazonaws.com/public/openphone-public-api-v1-prod.json

      - name: Generate TypeScript types
        run: bun run generate:types

      - name: Run linter
        run: bun run lint

      - name: Run formatter check
        run: bun run format --check

      - name: Run tests
        run: bun run test

      - name: Build project
        run: bun run build

      - name: Check build output
        run: |
          if [ ! -d "dist" ]; then
            echo "Build failed - dist directory not found"
            exit 1
          fi
          
          if [ ! -f "dist/index.js" ]; then
            echo "Build failed - index.js not found"
            exit 1
          fi
          
          if [ ! -f "dist/index.d.ts" ]; then
            echo "Build failed - index.d.ts not found"
            exit 1
          fi
          
          echo "Build successful - all required files present"

      - name: Check file sizes
        run: |
          echo "Build output sizes:"
          ls -lh dist/
          
          # Check if bundle is too large (warn if > 100KB)
          SIZE=$(stat -c%s dist/index.js)
          if [ $SIZE -gt 102400 ]; then
            echo "Warning: Bundle size is larger than 100KB ($SIZE bytes)"
          else
            echo "Bundle size is acceptable ($SIZE bytes)"
          fi
