name: Release

on:
  release:
    types: [ published ]

jobs:
  release:
    name: Publish Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Generate TypeScript types
        run: bun run generate:types

      - name: Build project
        run: bun run build

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.release.tag_name }}
          release_name: ${{ github.event.release.name }}
          body: |
            ## OpenPhone API SDK ${{ github.event.release.tag_name }}
            
            ### What's New
            - TypeScript SDK for OpenPhone Public API
            - Full type safety with auto-generated types
            - Support for calls, messages, phone numbers, and webhooks
            - Modern ES modules with tree-shaking support
            
            ### Installation
            ```bash
            npm install @openphone/api-sdk
            ```
            
            ### Quick Start
            ```typescript
            import { OpenPhoneClient } from '@openphone/api-sdk';
            
            const client = new OpenPhoneClient({
              apiKey: 'your-api-key-here',
            });
            
            // List phone numbers
            const phoneNumbers = await client.listPhoneNumbers();
            ```
            
            ### Documentation
            - [Full Documentation](https://github.com/openphone/openphone-api-sdk#readme)
            - [API Reference](https://github.com/openphone/openphone-api-sdk#api-reference)
            - [Examples](https://github.com/openphone/openphone-api-sdk/tree/main/examples)
          draft: false
          prerelease: false
